### ISSUE TITLE
Feature Request: Dark theme preview

### ISSUE THREAD

**Issue by exoego** [corocn/slackemojigen#10]
Slack added dark theme support last year.
I would like to make custom emojis looks good both on light theme and dark theme.

I think previewing on light/dark theme in parallel makes it easier to choose a color looks good on both background.
![image](https://user-images.githubusercontent.com/127635/75836089-15fcf180-5e04-11ea-9182-931066dbfc7e.png)

**Comment by corocn** [comment]
Sorry it took me so long to confirm! It's a cool suggestion. There are many ways to implement it, but I don't think it's that difficult, so I'll implement it.

Of course, PR is also welcome.

**Comment by corocn** [comment]
released

![image](https://user-images.githubusercontent.com/1762675/133455716-eff1b73b-f670-40f2-b9d9-0947f4e768c5.png)

**Comment by corocn** [comment]
https://github.com/corocn/slackemojigen/commit/b2c182ed4ba4508ece798f5dc4637b35fc6c40f8
