### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by exoego** [corocn/slackemojigen#4]
Please consider to specify license, so that users understand what kind of contribution/utilization are allowed.

https://choosealicense.com/
https://help.github.com/en/articles/licensing-a-repository

**Comment by exoego** [comment]
Addressed in https://github.com/corocn/slackemojigen/commit/3e78cb787574f4ff9814ffc359345b4448a5f9fa

**Comment by corocn** [comment]
also fixing README.md now
