### ISSUE TITLE
Consider OGP/Twitter Card for sharing

### ISSUE THREAD

**Issue by exoego** [corocn/slackemojigen#5]
It would be great if slackemogigen has below, so sharing slackemogigen on SNS is more amusing.

* Twitter card https://developer.twitter.com/en/docs/basics/getting-started
* Open Graph protocol https://ogp.me/
    * Slack, Facebook and other SNS

**Comment by corocn** [comment]
COOL!
I will address it.

**Comment by corocn** [comment]
@exoego done!
![image](https://user-images.githubusercontent.com/1762675/62846379-d9a06180-bd0a-11e9-8e55-04f9b78db30c.png)
